version: '3'

services:
  first-container:
    container_name: 'first-container'
    build: ./container_1
    ports:
      - 3000:3000
  second-container:
    container_name: 'second-container'
    build: ./container_2
    ports:
      - 3001:3001
  reverse-proxy:
    container_name: 'reverse-proxy'
    build: ./reverse-proxy
    ports:
      - 80:80
    environment:
      - URL_C1=http://host.docker.internal:3000/
      - URL_C2=http://host.docker.internal:3001/
    # envsubstでテンプレートに環境変数を埋め込んで、それを > nginx.confで出力している
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
