version: '3'

services:
  first-container:
    container_name: 'first-container'
    build: ./container_1
    ports:
      - 3000:80
  
  second-container:
    container_name: 'second-container'
    build: ./container_2
    ports:
      - 3001:80

  reverse-proxy:
    container_name: 'reverse-proxy'
    build: ./reverse-proxy
    ports:
      - 80:80